# Generated by Django 4.1.5 on 2023-02-11 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='percentagepgra',
            new_name='percentagegra',
        ),
    ]
